import { Container } from "@/components/shared";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Skill Up",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header></header>
      <main className="min-h-screen">{children}</main>
      <footer>
        <Container>©Сreator and Author by Bodich</Container>
      </footer>
    </>
  );
}
