import { Open_Sans, PT_Sans } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/shared/providers";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";

const openSans = Open_Sans({
  subsets: ["cyrillic"],
  variable: "--font-opensans",
  weight: ["400", "700", "300"],
});

const ptSans = PT_Sans({
  subsets: ["cyrillic"],
  variable: "--font-ptsans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Next Skill Up",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="ru" className="dark">
        <head>
          <link data-rh="true" rel="icon" href="/logo.png" />
        </head>
        <body className={`${openSans.className} ${ptSans.variable}`}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </SessionProvider>
  );
}
