import { Open_Sans, PT_Sans } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["cyrillic"],
  variable: "--font-opensans",
  weight: ["400", "700", "300"],
});

const ptSans = PT_Sans({
  subsets: ["cyrillic"],
  variable: "--font-ptsans",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Next Skill Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="dark">
      <head>
        <link data-rh="true" rel="icon" href="/logo.png" />
      </head>
      <body className={`${openSans.className} ${ptSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
